pipeline:
  test-image:
    image: docker
    commands:
      - docker build --rm -t fpfis/twin-varnish-${DRONE_COMMIT_SHA} .
      - docker run --rm -i fpfis/twin-varnish-${DRONE_COMMIT_SHA} twin-varnish --version
      - docker run -d fpfis/twin-varnish-${DRONE_COMMIT_SHA}|tr -d '\n' > .container-id
      - sleep 5
      - docker exec -i $(cat .container-id) /tests/test.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  clean-workspace:
    image: docker
    commands:
      - docker rm -f $(cat .container-id)
      - docker rmi -f fpfis/twin-varnish-${DRONE_COMMIT_SHA}
      - rm .container-id
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      status: [ failure, success ]

  build-and-push-image:
    image: plugins/docker
    repo: fpfis/twin-varnish
    tags:
      - latest
      - ${DRONE_TAG}
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

