pipeline:
  test-image:
    image: docker
    commands:
      - docker build --rm -t fpfis/twin-varnish-${DRONE_COMMIT_SHA} .
      - docker run --rm -i fpfis/twin-varnish-${DRONE_COMMIT_SHA} varnishd -V
      - docker run -d fpfis/twin-varnish-${DRONE_COMMIT_SHA}|tr -d '\n' > .container-id
      - sleep 5
      - docker exec -i $(cat .container-id) /tests/test.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  clean-workspace:
    image: docker
    commands:
      - docker rm -f $(cat .container-id)
      - docker rmi -f fpfis/twin-varnish-${DRONE_COMMIT_SHA}
      - rm .container-id
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      status: [ failure, success ]

  slack-notify-test:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: ci
    username: fpfisbot
    icon_url: https://avatars0.githubusercontent.com/u/23079543?v=3&s=400
    when:
      event: push
      status: success
    template: >
      Salt formula twin-varnish@${DRONE_BRANCH} tests <{{build.link}}|passed>.

  build-and-push-image:
    image: plugins/docker
    repo: fpfis/twin-varnish
    tags:
      - latest
      - ${DRONE_TAG}
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

  slack-notify-tag:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: ci
    username: fpfisbot
    icon_url: https://avatars0.githubusercontent.com/u/23079543?v=3&s=400
    when:
      event: tag
      status: success
    template: >
      Docker image fpfis/twin-varnish:${DRONE_TAG} <{{build.link}}|published> on DockerHub.